### ISSUE TITLE
MAc

### ISSUE THREAD

**Issue by ValiantCat** [Urinx/Iconista#2]

**Comment by ValiantCat** [comment]
mac OS X 10.11  你需要更新了呦  我一直在用

**Comment by Urinx** [comment]
@aiqiuqiu 好嘞，我看看哈

**Comment by Urinx** [comment]
@aiqiuqiu 最近比较忙，昨天才看了下，原来是El Capitan新加了rootless安全机制，限制了对系统自带App的修改，这个表示无能为力。对此，我已经更新并兼容10.11了。当然啦，自带app的图标也还是有方法替换，具体的可以看README，里面有详细解释。
你再看看还有啥问题，没有的话就可以close了。 :smiley:

**Comment by ValiantCat** [comment]
好多 多谢
