### ISSUE TITLE
OSX 10.11

### ISSUE THREAD

**Issue by ValiantCat** [Urinx/Iconista#3]

**Comment by ValiantCat** [comment]
我把OSX 10.11的rootless关掉了  但是 最后输出了一下This is Not Support Now 肿么办

**Comment by Urinx** [comment]
@aiqiuqiu 最后那个`This is Not Support Now`是替换系统硬盘，文件夹，各种类型的文件等图标，我没相应的图标，而且要替换的太多了，所有这个功能暂时就不支持了。。

**Comment by ValiantCat** [comment]
我发现 关掉了 rootless  执行你旧的命令 直接就好了 
没必要用新的命令 亲测可用  你可以更新一下

**Comment by Urinx** [comment]
@aiqiuqiu 哦哦，这个我自己没试过-_-||。反正也不是什么大问题啦，下次再一起更新。用完后还是开启rootless吧，安全重要。

**Comment by ValiantCat** [comment]
恩恩
